[tool.poetry]
name = "cypress"
version = "0.1.0"
description = ""
authors = ["Grayson Miller <grayson.miller124@gmail.com>"]
readme = "README.md"
packages = [{include = "cypress", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
Pillow = "^9.3.0"
numpy = "^1.23.5"
matplotlib = "^3.6.2"
networkx = "^2.8.8"
pygraphviz = "^1.10"
dearpygui = "^1.8.0"
pyglfw = "^0.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
cypress = "cypress.__main__:main"
cyp = "cypress.__main__:main"